-- Aggregates

/*
    COUNT() - count rows with non-null values
    SUM() - adds up numeric values 
    AVG() - Finds the average of the numeric valeus
    MIN()
    MAX()

*/
-- list all entries in the Order Details table
SELECT *
FROM OrderDetails

-- count
SELECT COUNT(*) as [Count of Orders]
FROM OrderDetails

-- Count the number of customers that have a Region Code
SELECT COUNT(RegionCode) as CustomerCount
FROM Customers
--182

-- get product information along with the number of times 
-- each product has been ordered
-- and the total quantity ordered
-- prod id, prod name, TotalOrderQuantity, TotalProductQuantity
SELECT p.ProductID, p.ProductName, COUNT(od.OrderID) as TotalOrderQuantity, SUM(od.Quantity) as TotalProductQuantity
FROM Products as p
LEFT OUTER JOIN OrderDetails as od
    ON p.ProductID = od.ProductID
-- LEFT OUTER JOIN Orders as o
--     ON od.OrderID = o.OrderID
GROUP BY p.ProductID, p.ProductName
ORDER BY TotalProductQuantity DESC


-- COUNT
SELECT COUNT(*) AS AllCount, -- Count all rows containing a value in any column
COUNT(RegionCode) as RegionCount, -- Count all rows containing a value in regionCode
COUNT(DISTINCT RegionCode) as DistinctRegionCode -- counts all unique 
FROM Customers

-- Numeric Aggregation
SELECT COUNT(Quantity) as Count,
SUM(Quantity) as [Sum of Quantity]
FROM OrderDetails

-- TOP
SELECT TOP(5) *
FROM OrderDetails
ORDER BY Quantity DESC
-- multiple dupicate quantities

SELECT TOP(5) WITH TIES *
FROM OrderDetails
ORDER BY Quantity DESC

-- Order Details Stats
SELECT OrderID,
COUNT(Quantity) AS [Number of Rows],
SUM(Quantity) as [Total Quantity Ordered],
AVG(Quantity) as [Average QTY per Line Item],
MIN(Quantity) as [Smallest],
MAX(Quantity) as [Largest]
FROM OrderDetails
GROUP BY OrderID
ORDER BY [Largest] DESC

-- calculate the first and last order date for each customer
SELECT c.CustomerID, c.CompanyName,
MIN(o.OrderDate) as [FirstOrder], MAX(o.OrderDate) as [LastOrder]
FROM Customers as c
INNER JOIN Orders as o
    ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID, c.CompanyName

-- calculate total revenue generated by each category in the Products table
-- sort by descending revenue
SELECT cat.CategoryName,
    SUM((od.UnitPrice * od.Quantity) * (1 - od.Discount)) as TotalRevenue
FROM Categories as cat
JOIN Products as p
    ON cat.CategoryID = p.CategoryID
JOIN OrderDetails as od
    ON p.ProductID = od.ProductID
GROUP BY cat.CategoryName
ORDER BY TotalRevenue DESC

--Fix Total Revenue to Currency
SELECT cat.CategoryName,
    FORMAT(SUM((od.UnitPrice * od.Quantity) * (1 - od.Discount)), 'C') as TotalRevenue
FROM Categories as cat
JOIN Products as p
    ON cat.CategoryID = p.CategoryID
JOIN OrderDetails as od
    ON p.ProductID = od.ProductID
GROUP BY cat.CategoryName
ORDER BY TotalRevenue DESC
-- FORMAT chages the rules of sorting -- now sorted alphabetically

-- Option 1: Order by the Equation
SELECT cat.CategoryName,
    FORMAT(SUM((od.UnitPrice * od.Quantity) * (1 - od.Discount)), 'C') as TotalRevenue
FROM Categories as cat
JOIN Products as p
    ON cat.CategoryID = p.CategoryID
JOIN OrderDetails as od
    ON p.ProductID = od.ProductID
GROUP BY cat.CategoryName
ORDER BY SUM((od.UnitPrice * od.Quantity) * (1 - od.Discount)) DESC

-- Option 2 Subquery

USE GalacticDepot

USE [master];
GO

RESTORE DATABASE [GalacticDepot]
FROM DISK = N'/var/opt/mssql/backup/GalacticDepot.bak'
WITH 
    MOVE 'GalacticDepot' TO '/var/opt/mssql/data/GalacticDepot.mdf',
    MOVE 'GalacticDepot_log' TO '/var/opt/mssql/data/GalacticDepot_log.ldf',
    REPLACE;
GO